### PR TITLE
Added basic psuedo functionality for the Kerberos_SDR class 

### PR DESCRIPTION
**Pull request by ryan-whittaker**
Additionally refactored that class due to acronym in class name (pep8)

You can now generate random data from this class, see class for details.

### CODE REVIEW

**Review by samuel-stulman — COMMENTED** [review]
Looks good to me for an initial base. Would like another member or two to agree before approving.

**Comment by Leon753** [comment]
Could you leave an explanation on what DOA is and the reasoning behind using a random number between 0 to 360.

**Comment by ryan-whittaker** [comment]
I put a pretty detailed explanation in the class's only public function for everyone to easily digest who needs it, I'm not sure what additional info I can really provide.

"""Primary and possibly only public function for this class. 
        
        Returns the calculated 'Direction of Arrival' of our anticipated signal. 
        This return value will be an integer indicating degrees in relation to current direction of travel ranging between 0 and 359.
        
        As of now, we believe this number will update approximately once every second, but this could change. Therefore, we will ensure that excessive polling via this does not hinder performance as we will simply return cached values when applicable.
        Additionally, you will be able to use the optional parameter to return real or dummy data.
        NOTE: Until this note is removed, this function will only return dummy data. Currently, it is simply random dummy data by default.
        """

**Comment by ryan-whittaker** [comment]
The purpose for the dummy data is so that people can structure their code who need to use that function. We will add more simulation based dummy data as the needs/project progresses but I wanted to at least stub out something asap in a method and format that others can count on being available throughout the project.

**Review by Leon753 — APPROVED** [review]
I didn't see those comments the first time, looks good!

**Review by kevinzwang — APPROVED** [review]

**Pull request merged**
